#!/usr/bin/env ruby
# frozen_string_literal: true

# Bundle CSS and JS assets for Propshaft (Rails 8) compatibility
# Run this once: ruby bundle_assets.rb

require 'fileutils'

puts "Bundling Comfortable Mexican Sofa assets for Propshaft..."

# === CSS BUNDLING ===
css_files = [
  "app/assets/stylesheets/comfy/vendor/bootstrap.min.css",
  "app/assets/stylesheets/comfy/vendor/codemirror.css",
  "app/assets/javascripts/comfy/vendor/codemirror/addon/fold/foldgutter.css",
  "app/assets/stylesheets/comfy/vendor/fontawesome.css",
  "app/assets/stylesheets/comfy/vendor/redactor.css",
  "app/assets/stylesheets/comfy/vendor/flatpickr.min.css",
  "app/assets/stylesheets/comfy/admin/cms/codemirror_overrides.css",
  "app/assets/stylesheets/comfy/admin/cms/redactor_overrides.css",
  "app/assets/stylesheets/comfy/admin/cms/base.css",
  "app/assets/stylesheets/comfy/admin/cms/custom.css"
]

css_output = "app/assets/stylesheets/comfy/admin/cms/application.css"

File.open(css_output, "w") do |out|
  out.puts "/*"
  out.puts " * Comfortable Mexican Sofa Admin Styles"
  out.puts " * Pre-bundled for Rails 8 Propshaft compatibility"
  out.puts " * "
  out.puts " * This file is automatically generated. Do not edit directly."
  out.puts " * To rebuild: ruby bundle_assets.rb"
  out.puts " */\n\n"

  css_files.each do |file|
    if File.exist?(file)
      puts "  Adding: #{file}"
      out.puts "/* === #{File.basename(file)} === */"
      out.puts File.read(file)
      out.puts "\n"
    else
      puts "  ⚠️  Warning: #{file} not found, skipping..."
    end
  end
end

puts "✅ CSS bundled: #{css_output}"

# === JAVASCRIPT BUNDLING ===
js_files = [
  # Core vendor libraries (must be in order)
  "app/assets/javascripts/comfy/vendor/codemirror.js",
  "app/assets/javascripts/comfy/vendor/codemirror/mode/css/css.js",
  "app/assets/javascripts/comfy/vendor/codemirror/mode/htmlmixed/htmlmixed.js",
  "app/assets/javascripts/comfy/vendor/codemirror/mode/javascript/javascript.js",
  "app/assets/javascripts/comfy/vendor/codemirror/mode/markdown/markdown.js",
  "app/assets/javascripts/comfy/vendor/codemirror/mode/xml/xml.js",
  "app/assets/javascripts/comfy/vendor/codemirror/addon/edit/closetag.js",
  "app/assets/javascripts/comfy/vendor/codemirror/addon/fold/foldcode.js",
  "app/assets/javascripts/comfy/vendor/codemirror/addon/fold/brace-fold.js",
  "app/assets/javascripts/comfy/vendor/codemirror/addon/fold/foldgutter.js",
  "app/assets/javascripts/comfy/vendor/sortable.min.js",
  "app/assets/javascripts/comfy/vendor/bootstrap.bundle.min.js",
  "app/assets/javascripts/comfy/vendor/diff/diff_match_patch.min.js",
  "app/assets/javascripts/comfy/vendor/diff/pretty_text_diff.js",
  "app/assets/javascripts/comfy/vendor/fontawesome.js",
  "app/assets/javascripts/comfy/vendor/redactor.js",
  "app/assets/javascripts/comfy/vendor/redactor/filemanager.js",
  "app/assets/javascripts/comfy/vendor/redactor/imagemanager.js",
  "app/assets/javascripts/comfy/vendor/redactor/definedlinks.js",
  "app/assets/javascripts/comfy/vendor/redactor/table.js",
  "app/assets/javascripts/comfy/vendor/redactor/video.js"
]

# Add all redactor i18n files
redactor_i18n = Dir.glob("app/assets/javascripts/comfy/vendor/redactor/i18n/*.js").sort
js_files.concat(redactor_i18n)

# Add flatpickr and its i18n files
js_files << "app/assets/javascripts/comfy/vendor/flatpickr.min.js"
flatpickr_i18n = Dir.glob("app/assets/javascripts/comfy/vendor/flatpickr/i18n/*.js").sort
js_files.concat(flatpickr_i18n)

js_output = "app/assets/builds/comfy_vendor.js"

File.open(js_output, "w") do |out|
  out.puts "/*"
  out.puts " * Comfortable Mexican Sofa Admin JavaScript"
  out.puts " * Pre-bundled for Rails 8 Propshaft compatibility"
  out.puts " * "
  out.puts " * This file is automatically generated. Do not edit directly."
  out.puts " * To rebuild: ruby bundle_assets.rb"
  out.puts " * "
  out.puts " * DEPENDENCIES (must be loaded before this file):"
  out.puts " * - rails-ujs (from @rails/ujs or rails)"
  out.puts " * - jquery3 (from jquery-rails gem)"
  out.puts " */\n\n"

  js_files.each do |file|
    if File.exist?(file)
      puts "  Adding: #{file}"
      out.puts "\n/* === #{file.sub('app/assets/javascripts/comfy/', '')} === */"
      out.puts File.read(file)
      out.puts ";" # Ensure each file ends with semicolon to prevent concatenation issues
    else
      puts "⚠️  Warning: #{file} not found, skipping..."
    end
  end
end

puts "✅ JavaScript bundled: #{js_output}"
puts "\n🎉 Asset bundling complete!"
puts "\nBundled files:"
puts "  - #{css_output} (#{File.size(css_output) / 1024}KB)"
puts "  - #{js_output} (#{File.size(js_output) / 1024}KB)"
puts "\nThese files are now ready for Propshaft (Rails 8)."
